<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

		DB::table('countries')->insert([
			['id' => '1', 'name' => 'AF', 'full_name' => 'Afghanistan','iso3' => 'AFG','numcode' => '4','phone_code' => '93'],
			['id' => '2', 'name' => 'AL', 'full_name' => 'Albania','iso3' => 'ALB','numcode' => '8','phone_code' => '355'],
			['id' => '3', 'name' => 'DZ', 'full_name' => 'Algeria','iso3' => 'DZA','numcode' => '12','phone_code' => '213'],
			['id' => '4', 'name' => 'AS', 'full_name' => 'American Samoa','iso3' => 'ASM','numcode' => '16','phone_code' => '1684'],
			['id' => '5', 'name' => 'AD', 'full_name' => 'Andorra','iso3' => 'AND','numcode' => '20','phone_code' => '376'],
			['id' => '6', 'name' => 'AO', 'full_name' => 'Angola','iso3' => 'AGO','numcode' => '24','phone_code' => '244'],
			['id' => '7', 'name' => 'AI', 'full_name' => 'Anguilla','iso3' => 'AIA','numcode' => '660','phone_code' => '1264'],
			['id' => '8', 'name' => 'AG', 'full_name' => 'Antigua and Barbuda','iso3' => 'ATG','numcode' => '28','phone_code' => '1268'],
			['id' => '9', 'name' => 'AR', 'full_name' => 'Argentina','iso3' => 'ARG','numcode' => '32','phone_code' => '54'],
			['id' => '10', 'name' => 'AM', 'full_name' => 'Armenia','iso3' => 'ARM','numcode' => '51','phone_code' => '374'],
			['id' => '11', 'name' => 'AW', 'full_name' => 'Aruba','iso3' => 'ABW','numcode' => '533','phone_code' => '297'],
			['id' => '12', 'name' => 'AU', 'full_name' => 'Australia','iso3' => 'AUS','numcode' => '36','phone_code' => '61'],
			['id' => '13', 'name' => 'AT', 'full_name' => 'Austria','iso3' => 'AUT','numcode' => '40','phone_code' => '43'],
			['id' => '14', 'name' => 'AZ', 'full_name' => 'Azerbaijan','iso3' => 'AZE','numcode' => '31','phone_code' => '994'],
			['id' => '15', 'name' => 'BS', 'full_name' => 'Bahamas','iso3' => 'BHS','numcode' => '44','phone_code' => '1242'],
			['id' => '16', 'name' => 'BH', 'full_name' => 'Bahrain','iso3' => 'BHR','numcode' => '48','phone_code' => '973'],
			['id' => '17', 'name' => 'BD', 'full_name' => 'Bangladesh','iso3' => 'BGD','numcode' => '50','phone_code' => '880'],
			['id' => '18', 'name' => 'BB', 'full_name' => 'Barbados','iso3' => 'BRB','numcode' => '52','phone_code' => '1246'],
			['id' => '19', 'name' => 'BY', 'full_name' => 'Belarus','iso3' => 'BLR','numcode' => '112','phone_code' => '375'],
			['id' => '20', 'name' => 'BE', 'full_name' => 'Belgium','iso3' => 'BEL','numcode' => '56','phone_code' => '32'],
			['id' => '21', 'name' => 'BZ', 'full_name' => 'Belize','iso3' => 'BLZ','numcode' => '84','phone_code' => '501'],
			['id' => '22', 'name' => 'BJ', 'full_name' => 'Benin','iso3' => 'BEN','numcode' => '204','phone_code' => '229'],
			['id' => '23', 'name' => 'BM', 'full_name' => 'Bermuda','iso3' => 'BMU','numcode' => '60','phone_code' => '1441'],
			['id' => '24', 'name' => 'BT', 'full_name' => 'Bhutan','iso3' => 'BTN','numcode' => '64','phone_code' => '975'],
			['id' => '25', 'name' => 'BO', 'full_name' => 'Bolivia','iso3' => 'BOL','numcode' => '68','phone_code' => '591'],
			['id' => '26', 'name' => 'BA', 'full_name' => 'Bosnia and Herzegovina','iso3' => 'BIH','numcode' => '70','phone_code' => '387'],
			['id' => '27', 'name' => 'BW', 'full_name' => 'Botswana','iso3' => 'BWA','numcode' => '72','phone_code' => '267'],
			['id' => '28', 'name' => 'BR', 'full_name' => 'Brazil','iso3' => 'BRA','numcode' => '76','phone_code' => '55'],
			['id' => '29', 'name' => 'BN', 'full_name' => 'Brunei Darussalam','iso3' => 'BRN','numcode' => '96','phone_code' => '673'],
			['id' => '30', 'name' => 'BG', 'full_name' => 'Bulgaria','iso3' => 'BGR','numcode' => '100','phone_code' => '359'],
			['id' => '31', 'name' => 'BF', 'full_name' => 'Burkina Faso','iso3' => 'BFA','numcode' => '854','phone_code' => '226'],
			['id' => '32', 'name' => 'BI', 'full_name' => 'Burundi','iso3' => 'BDI','numcode' => '108','phone_code' => '257'],
			['id' => '33', 'name' => 'KH', 'full_name' => 'Cambodia','iso3' => 'KHM','numcode' => '116','phone_code' => '855'],
			['id' => '34', 'name' => 'CM', 'full_name' => 'Cameroon','iso3' => 'CMR','numcode' => '120','phone_code' => '237'],
			['id' => '35', 'name' => 'CA', 'full_name' => 'Canada','iso3' => 'CAN','numcode' => '124','phone_code' => '1'],
			['id' => '36', 'name' => 'CV', 'full_name' => 'Cape Verde','iso3' => 'CPV','numcode' => '132','phone_code' => '238'],
			['id' => '37', 'name' => 'KY', 'full_name' => 'Cayman Islands','iso3' => 'CYM','numcode' => '136','phone_code' => '1345'],
			['id' => '38', 'name' => 'CF', 'full_name' => 'Central African Republic','iso3' => 'CAF','numcode' => '140','phone_code' => '236'],
			['id' => '39', 'name' => 'TD', 'full_name' => 'Chad','iso3' => 'TCD','numcode' => '148','phone_code' => '235'],
			['id' => '40', 'name' => 'CL', 'full_name' => 'Chile','iso3' => 'CHL','numcode' => '152','phone_code' => '56'],
			['id' => '41', 'name' => 'CN', 'full_name' => 'China','iso3' => 'CHN','numcode' => '156','phone_code' => '86'],
			['id' => '42', 'name' => 'CO', 'full_name' => 'Colombia','iso3' => 'COL','numcode' => '170','phone_code' => '57'],
			['id' => '43', 'name' => 'KM', 'full_name' => 'Comoros','iso3' => 'COM','numcode' => '174','phone_code' => '269'],
			['id' => '44', 'name' => 'CG', 'full_name' => 'Congo','iso3' => 'COG','numcode' => '178','phone_code' => '242'],
			['id' => '45', 'name' => 'CK', 'full_name' => 'Cook Islands','iso3' => 'COK','numcode' => '184','phone_code' => '682'],
			['id' => '46', 'name' => 'CR', 'full_name' => 'Costa Rica','iso3' => 'CRI','numcode' => '188','phone_code' => '506'],
			['id' => '47', 'name' => 'CI', 'full_name' => 'Cote D\'Ivoire','iso3' => 'CIV','numcode' => '384','phone_code' => '225'],
			['id' => '48', 'name' => 'HR', 'full_name' => 'Croatia','iso3' => 'HRV','numcode' => '191','phone_code' => '385'],
			['id' => '49', 'name' => 'CU', 'full_name' => 'Cuba','iso3' => 'CUB','numcode' => '192','phone_code' => '53'],
			['id' => '50', 'name' => 'CY', 'full_name' => 'Cyprus','iso3' => 'CYP','numcode' => '196','phone_code' => '357'],
			['id' => '51', 'name' => 'CZ', 'full_name' => 'Czech Republic','iso3' => 'CZE','numcode' => '203','phone_code' => '420'],
			['id' => '52', 'name' => 'DK', 'full_name' => 'Denmark','iso3' => 'DNK','numcode' => '208','phone_code' => '45'],
			['id' => '53', 'name' => 'DJ', 'full_name' => 'Djibouti','iso3' => 'DJI','numcode' => '262','phone_code' => '253'],
			['id' => '54', 'name' => 'DM', 'full_name' => 'Dominica','iso3' => 'DMA','numcode' => '212','phone_code' => '1767'],
			['id' => '55', 'name' => 'DO', 'full_name' => 'Dominican Republic','iso3' => 'DOM','numcode' => '214','phone_code' => '1809'],
			['id' => '56', 'name' => 'EC', 'full_name' => 'Ecuador','iso3' => 'ECU','numcode' => '218','phone_code' => '593'],
			['id' => '57', 'name' => 'EG', 'full_name' => 'Egypt','iso3' => 'EGY','numcode' => '818','phone_code' => '20'],
			['id' => '58', 'name' => 'SV', 'full_name' => 'El Salvador','iso3' => 'SLV','numcode' => '222','phone_code' => '503'],
			['id' => '59', 'name' => 'GQ', 'full_name' => 'Equatorial Guinea','iso3' => 'GNQ','numcode' => '226','phone_code' => '240'],
			['id' => '60', 'name' => 'ER', 'full_name' => 'Eritrea','iso3' => 'ERI','numcode' => '232','phone_code' => '291'],
			['id' => '61', 'name' => 'EE', 'full_name' => 'Estonia','iso3' => 'EST','numcode' => '233','phone_code' => '372'],
			['id' => '62', 'name' => 'ET', 'full_name' => 'Ethiopia','iso3' => 'ETH','numcode' => '231','phone_code' => '251'],
			['id' => '63', 'name' => 'FK', 'full_name' => 'Falkland Islands','iso3' => 'FLK','numcode' => '238','phone_code' => '500'],
			['id' => '64', 'name' => 'FO', 'full_name' => 'Faroe Islands','iso3' => 'FRO','numcode' => '234','phone_code' => '298'],
			['id' => '65', 'name' => 'FJ', 'full_name' => 'Fiji','iso3' => 'FJI','numcode' => '242','phone_code' => '679'],
			['id' => '66', 'name' => 'FI', 'full_name' => 'Finland','iso3' => 'FIN','numcode' => '246','phone_code' => '358'],
			['id' => '67', 'name' => 'FR', 'full_name' => 'France','iso3' => 'FRA','numcode' => '250','phone_code' => '33'],
			['id' => '68', 'name' => 'GF', 'full_name' => 'French Guiana','iso3' => 'GUF','numcode' => '254','phone_code' => '594'],
			['id' => '69', 'name' => 'PF', 'full_name' => 'French Polynesia','iso3' => 'PYF','numcode' => '258','phone_code' => '689'],
			['id' => '70', 'name' => 'GA', 'full_name' => 'Gabon','iso3' => 'GAB','numcode' => '266','phone_code' => '241'],
			['id' => '71', 'name' => 'GM', 'full_name' => 'Gambia','iso3' => 'GMB','numcode' => '270','phone_code' => '220'],
			['id' => '72', 'name' => 'GE', 'full_name' => 'Georgia','iso3' => 'GEO','numcode' => '268','phone_code' => '995'],
			['id' => '73', 'name' => 'DE', 'full_name' => 'Germany','iso3' => 'DEU','numcode' => '276','phone_code' => '49'],
			['id' => '74', 'name' => 'GH', 'full_name' => 'Ghana','iso3' => 'GHA','numcode' => '288','phone_code' => '233'],
			['id' => '75', 'name' => 'GI', 'full_name' => 'Gibraltar','iso3' => 'GIB','numcode' => '292','phone_code' => '350'],
			['id' => '76', 'name' => 'GR', 'full_name' => 'Greece','iso3' => 'GRC','numcode' => '300','phone_code' => '30'],
			['id' => '77', 'name' => 'GL', 'full_name' => 'Greenland','iso3' => 'GRL','numcode' => '304','phone_code' => '299'],
			['id' => '78', 'name' => 'GD', 'full_name' => 'Grenada','iso3' => 'GRD','numcode' => '308','phone_code' => '1473'],
			['id' => '79', 'name' => 'GP', 'full_name' => 'Guadeloupe','iso3' => 'GLP','numcode' => '312','phone_code' => '590'],
			['id' => '80', 'name' => 'GU', 'full_name' => 'Guam','iso3' => 'GUM','numcode' => '316','phone_code' => '1671'],
			['id' => '81', 'name' => 'GT', 'full_name' => 'Guatemala','iso3' => 'GTM','numcode' => '320','phone_code' => '502'],
			['id' => '82', 'name' => 'GN', 'full_name' => 'Guinea','iso3' => 'GIN','numcode' => '324','phone_code' => '224'],
			['id' => '83', 'name' => 'GW', 'full_name' => 'Guinea-Bissau','iso3' => 'GNB','numcode' => '624','phone_code' => '245'],
			['id' => '84', 'name' => 'GY', 'full_name' => 'Guyana','iso3' => 'GUY','numcode' => '328','phone_code' => '592'],
			['id' => '85', 'name' => 'HT', 'full_name' => 'Haiti','iso3' => 'HTI','numcode' => '332','phone_code' => '509'],
			['id' => '86', 'name' => 'HN', 'full_name' => 'Honduras','iso3' => 'HND','numcode' => '340','phone_code' => '504'],
			['id' => '87', 'name' => 'HK', 'full_name' => 'Hong Kong','iso3' => 'HKG','numcode' => '344','phone_code' => '852'],
			['id' => '88', 'name' => 'HU', 'full_name' => 'Hungary','iso3' => 'HUN','numcode' => '348','phone_code' => '36'],
			['id' => '89', 'name' => 'IS', 'full_name' => 'Iceland','iso3' => 'ISL','numcode' => '352','phone_code' => '354'],
			['id' => '90', 'name' => 'IN', 'full_name' => 'India','iso3' => 'IND','numcode' => '356','phone_code' => '91'],
			['id' => '91', 'name' => 'ID', 'full_name' => 'Indonesia','iso3' => 'IDN','numcode' => '360','phone_code' => '62'],
			['id' => '92', 'name' => 'IR', 'full_name' => 'Iran','iso3' => 'IRN','numcode' => '364','phone_code' => '98'],
			['id' => '93', 'name' => 'IQ', 'full_name' => 'Iraq','iso3' => 'IRQ','numcode' => '368','phone_code' => '964'],
			['id' => '94', 'name' => 'IE', 'full_name' => 'Ireland','iso3' => 'IRL','numcode' => '372','phone_code' => '353'],
			['id' => '95', 'name' => 'IL', 'full_name' => 'Israel','iso3' => 'ISR','numcode' => '376','phone_code' => '972'],
			['id' => '96', 'name' => 'IT', 'full_name' => 'Italy','iso3' => 'ITA','numcode' => '380','phone_code' => '39'],
			['id' => '97', 'name' => 'JM', 'full_name' => 'Jamaica','iso3' => 'JAM','numcode' => '388','phone_code' => '1876'],
			['id' => '98', 'name' => 'JP', 'full_name' => 'Japan','iso3' => 'JPN','numcode' => '392','phone_code' => '81'],
			['id' => '99', 'name' => 'JO', 'full_name' => 'Jordan','iso3' => 'JOR','numcode' => '400','phone_code' => '962'],
			['id' => '100', 'name' => 'KZ', 'full_name' => 'Kazakhstan','iso3' => 'KAZ','numcode' => '398','phone_code' => '7'],
			['id' => '101', 'name' => 'KE', 'full_name' => 'Kenya','iso3' => 'KEN','numcode' => '404','phone_code' => '254'],
			['id' => '102', 'name' => 'KI', 'full_name' => 'Kiribati','iso3' => 'KIR','numcode' => '296','phone_code' => '686'],
			['id' => '103', 'name' => 'KR', 'full_name' => 'Korea','iso3' => 'KOR','numcode' => '410','phone_code' => '82'],
			['id' => '104', 'name' => 'KW', 'full_name' => 'Kuwait','iso3' => 'KWT','numcode' => '414','phone_code' => '965'],
			['id' => '105', 'name' => 'KG', 'full_name' => 'Kyrgyzstan','iso3' => 'KGZ','numcode' => '417','phone_code' => '996'],
			['id' => '106', 'name' => 'LA', 'full_name' => 'Lao People\'s Democratic Republic','iso3' => 'LAO','numcode' => '418','phone_code' => '856'],
			['id' => '107', 'name' => 'LV', 'full_name' => 'Latvia','iso3' => 'LVA','numcode' => '428','phone_code' => '371'],
			['id' => '108', 'name' => 'LB', 'full_name' => 'Lebanon','iso3' => 'LBN','numcode' => '422','phone_code' => '961'],
			['id' => '109', 'name' => 'LS', 'full_name' => 'Lesotho','iso3' => 'LSO','numcode' => '426','phone_code' => '266'],
			['id' => '110', 'name' => 'LR', 'full_name' => 'Liberia','iso3' => 'LBR','numcode' => '430','phone_code' => '231'],
			['id' => '111', 'name' => 'LY', 'full_name' => 'Libyan Arab Jamahiriya','iso3' => 'LBY','numcode' => '434','phone_code' => '218'],
			['id' => '112', 'name' => 'LI', 'full_name' => 'Liechtenstein','iso3' => 'LIE','numcode' => '438','phone_code' => '423'],
			['id' => '113', 'name' => 'LT', 'full_name' => 'Lithuania','iso3' => 'LTU','numcode' => '440','phone_code' => '370'],
			['id' => '114', 'name' => 'LU', 'full_name' => 'Luxembourg','iso3' => 'LUX','numcode' => '442','phone_code' => '352'],
			['id' => '115', 'name' => 'MO', 'full_name' => 'Macao','iso3' => 'MAC','numcode' => '446','phone_code' => '853'],
			['id' => '116', 'name' => 'MK', 'full_name' => 'Macedonia','iso3' => 'MKD','numcode' => '807','phone_code' => '389'],
			['id' => '117', 'name' => 'MG', 'full_name' => 'Madagascar','iso3' => 'MDG','numcode' => '450','phone_code' => '261'],
			['id' => '118', 'name' => 'MW', 'full_name' => 'Malawi','iso3' => 'MWI','numcode' => '454','phone_code' => '265'],
			['id' => '119', 'name' => 'MY', 'full_name' => 'Malaysia','iso3' => 'MYS','numcode' => '458','phone_code' => '60'],
			['id' => '120', 'name' => 'MV', 'full_name' => 'Maldives','iso3' => 'MDV','numcode' => '462','phone_code' => '960'],
			['id' => '121', 'name' => 'ML', 'full_name' => 'Mali','iso3' => 'MLI','numcode' => '466','phone_code' => '223'],
			['id' => '122', 'name' => 'MT', 'full_name' => 'Malta','iso3' => 'MLT','numcode' => '470','phone_code' => '356'],
			['id' => '123', 'name' => 'MH', 'full_name' => 'Marshall Islands','iso3' => 'MHL','numcode' => '584','phone_code' => '692'],
			['id' => '124', 'name' => 'MQ', 'full_name' => 'Martinique','iso3' => 'MTQ','numcode' => '474','phone_code' => '596'],
			['id' => '125', 'name' => 'MR', 'full_name' => 'Mauritania','iso3' => 'MRT','numcode' => '478','phone_code' => '222'],
			['id' => '126', 'name' => 'MU', 'full_name' => 'Mauritius','iso3' => 'MUS','numcode' => '480','phone_code' => '230'],
			['id' => '127', 'name' => 'MX', 'full_name' => 'Mexico','iso3' => 'MEX','numcode' => '484','phone_code' => '52'],
			['id' => '128', 'name' => 'FM', 'full_name' => 'Micronesia','iso3' => 'FSM','numcode' => '583','phone_code' => '691'],
			['id' => '129', 'name' => 'MD', 'full_name' => 'Moldova','iso3' => 'MDA','numcode' => '498','phone_code' => '373'],
			['id' => '130', 'name' => 'MC', 'full_name' => 'Monaco','iso3' => 'MCO','numcode' => '492','phone_code' => '377'],
			['id' => '131', 'name' => 'MN', 'full_name' => 'Mongolia','iso3' => 'MNG','numcode' => '496','phone_code' => '976'],
			['id' => '132', 'name' => 'MS', 'full_name' => 'Montserrat','iso3' => 'MSR','numcode' => '500','phone_code' => '1664'],
			['id' => '133', 'name' => 'MA', 'full_name' => 'Morocco','iso3' => 'MAR','numcode' => '504','phone_code' => '212'],
			['id' => '134', 'name' => 'MZ', 'full_name' => 'Mozambique','iso3' => 'MOZ','numcode' => '508','phone_code' => '258'],
			['id' => '135', 'name' => 'MM', 'full_name' => 'Myanmar','iso3' => 'MMR','numcode' => '104','phone_code' => '95'],
			['id' => '136', 'name' => 'NA', 'full_name' => 'Namibia','iso3' => 'NAM','numcode' => '516','phone_code' => '264'],
			['id' => '137', 'name' => 'NR', 'full_name' => 'Nauru','iso3' => 'NRU','numcode' => '520','phone_code' => '674'],
			['id' => '138', 'name' => 'NP', 'full_name' => 'Nepal','iso3' => 'NPL','numcode' => '524','phone_code' => '977'],
			['id' => '139', 'name' => 'NL', 'full_name' => 'Netherlands','iso3' => 'NLD','numcode' => '528','phone_code' => '31'],
			['id' => '140', 'name' => 'AN', 'full_name' => 'Netherlands Antilles','iso3' => 'ANT','numcode' => '530','phone_code' => '599'],
			['id' => '141', 'name' => 'NC', 'full_name' => 'New Caledonia','iso3' => 'NCL','numcode' => '540','phone_code' => '687'],
			['id' => '142', 'name' => 'NZ', 'full_name' => 'New Zealand','iso3' => 'NZL','numcode' => '554','phone_code' => '64'],
			['id' => '143', 'name' => 'NI', 'full_name' => 'Nicaragua','iso3' => 'NIC','numcode' => '558','phone_code' => '505'],
			['id' => '144', 'name' => 'NE', 'full_name' => 'Niger','iso3' => 'NER','numcode' => '562','phone_code' => '227'],
			['id' => '145', 'name' => 'NG', 'full_name' => 'Nigeria','iso3' => 'NGA','numcode' => '566','phone_code' => '234'],
			['id' => '146', 'name' => 'NU', 'full_name' => 'Niue','iso3' => 'NIU','numcode' => '570','phone_code' => '683'],
			['id' => '147', 'name' => 'NF', 'full_name' => 'Norfolk Island','iso3' => 'NFK','numcode' => '574','phone_code' => '672'],
			['id' => '148', 'name' => 'MP', 'full_name' => 'Northern Mariana Islands','iso3' => 'MNP','numcode' => '580','phone_code' => '1670'],
			['id' => '149', 'name' => 'NO', 'full_name' => 'Norway','iso3' => 'NOR','numcode' => '578','phone_code' => '47'],
			['id' => '150', 'name' => 'OM', 'full_name' => 'Oman','iso3' => 'OMN','numcode' => '512','phone_code' => '968'],
			['id' => '151', 'name' => 'PK', 'full_name' => 'Pakistan','iso3' => 'PAK','numcode' => '586','phone_code' => '92'],
			['id' => '152', 'name' => 'PW', 'full_name' => 'Palau','iso3' => 'PLW','numcode' => '585','phone_code' => '680'],
			['id' => '153', 'name' => 'PA', 'full_name' => 'Panama','iso3' => 'PAN','numcode' => '591','phone_code' => '507'],
			['id' => '154', 'name' => 'PG', 'full_name' => 'Papua New Guinea','iso3' => 'PNG','numcode' => '598','phone_code' => '675'],
			['id' => '155', 'name' => 'PY', 'full_name' => 'Paraguay','iso3' => 'PRY','numcode' => '600','phone_code' => '595'],
			['id' => '156', 'name' => 'PE', 'full_name' => 'Peru','iso3' => 'PER','numcode' => '604','phone_code' => '51'],
			['id' => '157', 'name' => 'PH', 'full_name' => 'Philippines','iso3' => 'PHL','numcode' => '608','phone_code' => '63'],
			['id' => '158', 'name' => 'PN', 'full_name' => 'Pitcairn','iso3' => 'PCN','numcode' => '612','phone_code' => '0'],
			['id' => '159', 'name' => 'PL', 'full_name' => 'Poland','iso3' => 'POL','numcode' => '616','phone_code' => '48'],
			['id' => '160', 'name' => 'PT', 'full_name' => 'Portugal','iso3' => 'PRT','numcode' => '620','phone_code' => '351'],
			['id' => '161', 'name' => 'PR', 'full_name' => 'Puerto Rico','iso3' => 'PRI','numcode' => '630','phone_code' => '1787'],
			['id' => '162', 'name' => 'QA', 'full_name' => 'Qatar','iso3' => 'QAT','numcode' => '634','phone_code' => '974'],
			['id' => '163', 'name' => 'RE', 'full_name' => 'Reunion','iso3' => 'REU','numcode' => '638','phone_code' => '262'],
			['id' => '164', 'name' => 'RO', 'full_name' => 'Romania','iso3' => 'ROM','numcode' => '642','phone_code' => '40'],
			['id' => '165', 'name' => 'RU', 'full_name' => 'Russian Federation','iso3' => 'RUS','numcode' => '643','phone_code' => '70'],
			['id' => '166', 'name' => 'RW', 'full_name' => 'Rwanda','iso3' => 'RWA','numcode' => '646','phone_code' => '250'],
			['id' => '167', 'name' => 'SH', 'full_name' => 'Saint Helena','iso3' => 'SHN','numcode' => '654','phone_code' => '290'],
			['id' => '168', 'name' => 'KN', 'full_name' => 'Saint Kitts and Nevis','iso3' => 'KNA','numcode' => '659','phone_code' => '1869'],
			['id' => '169', 'name' => 'LC', 'full_name' => 'Saint Lucia','iso3' => 'LCA','numcode' => '662','phone_code' => '1758'],
			['id' => '170', 'name' => 'PM', 'full_name' => 'Saint Pierre and Miquelon','iso3' => 'SPM','numcode' => '666','phone_code' => '508'],
			['id' => '171', 'name' => 'VC', 'full_name' => 'Saint Vincent and the Grenadines','iso3' => 'VCT','numcode' => '670','phone_code' => '1784'],
			['id' => '172', 'name' => 'WS', 'full_name' => 'Samoa','iso3' => 'WSM','numcode' => '882','phone_code' => '684'],
			['id' => '173', 'name' => 'SM', 'full_name' => 'San Marino','iso3' => 'SMR','numcode' => '674','phone_code' => '378'],
			['id' => '174', 'name' => 'ST', 'full_name' => 'Sao Tome and Principe','iso3' => 'STP','numcode' => '678','phone_code' => '239'],
			['id' => '175', 'name' => 'SA', 'full_name' => 'Saudi Arabia','iso3' => 'SAU','numcode' => '682','phone_code' => '966'],
			['id' => '176', 'name' => 'SN', 'full_name' => 'Senegal','iso3' => 'SEN','numcode' => '686','phone_code' => '221'],
			['id' => '177', 'name' => 'SC', 'full_name' => 'Seychelles','iso3' => 'SYC','numcode' => '690','phone_code' => '248'],
			['id' => '178', 'name' => 'SL', 'full_name' => 'Sierra Leone','iso3' => 'SLE','numcode' => '694','phone_code' => '232'],
			['id' => '179', 'name' => 'SG', 'full_name' => 'Singapore','iso3' => 'SGP','numcode' => '702','phone_code' => '65'],
			['id' => '180', 'name' => 'SK', 'full_name' => 'Slovakia','iso3' => 'SVK','numcode' => '703','phone_code' => '421'],
			['id' => '181', 'name' => 'SI', 'full_name' => 'Slovenia','iso3' => 'SVN','numcode' => '705','phone_code' => '386'],
			['id' => '182', 'name' => 'SB', 'full_name' => 'Solomon Islands','iso3' => 'SLB','numcode' => '90','phone_code' => '677'],
			['id' => '183', 'name' => 'SO', 'full_name' => 'Somalia','iso3' => 'SOM','numcode' => '706','phone_code' => '252'],
			['id' => '184', 'name' => 'ZA', 'full_name' => 'South Africa','iso3' => 'ZAF','numcode' => '710','phone_code' => '27'],
			['id' => '185', 'name' => 'ES', 'full_name' => 'Spain','iso3' => 'ESP','numcode' => '724','phone_code' => '34'],
			['id' => '186', 'name' => 'LK', 'full_name' => 'Sri Lanka','iso3' => 'LKA','numcode' => '144','phone_code' => '94'],
			['id' => '187', 'name' => 'SD', 'full_name' => 'Sudan','iso3' => 'SDN','numcode' => '736','phone_code' => '249'],
			['id' => '188', 'name' => 'SR', 'full_name' => 'Surifull_name','iso3' => 'SUR','numcode' => '740','phone_code' => '597'],
			['id' => '189', 'name' => 'SJ', 'full_name' => 'Svalbard and Jan Mayen','iso3' => 'SJM','numcode' => '744','phone_code' => '47'],
			['id' => '190', 'name' => 'SZ', 'full_name' => 'Swaziland','iso3' => 'SWZ','numcode' => '748','phone_code' => '268'],
			['id' => '191', 'name' => 'SE', 'full_name' => 'Sweden','iso3' => 'SWE','numcode' => '752','phone_code' => '46'],
			['id' => '192', 'name' => 'CH', 'full_name' => 'Switzerland','iso3' => 'CHE','numcode' => '756','phone_code' => '41'],
			['id' => '193', 'name' => 'SY', 'full_name' => 'Syrian Arab Republic','iso3' => 'SYR','numcode' => '760','phone_code' => '963'],
			['id' => '194', 'name' => 'TW', 'full_name' => 'Taiwan','iso3' => 'TWN','numcode' => '158','phone_code' => '886'],
			['id' => '195', 'name' => 'TJ', 'full_name' => 'Tajikistan','iso3' => 'TJK','numcode' => '762','phone_code' => '992'],
			['id' => '196', 'name' => 'TZ', 'full_name' => 'Tanzania','iso3' => 'TZA','numcode' => '834','phone_code' => '255'],
			['id' => '197', 'name' => 'TH', 'full_name' => 'Thailand','iso3' => 'THA','numcode' => '764','phone_code' => '66'],
			['id' => '198', 'name' => 'TG', 'full_name' => 'Togo','iso3' => 'TGO','numcode' => '768','phone_code' => '228'],
			['id' => '199', 'name' => 'TK', 'full_name' => 'Tokelau','iso3' => 'TKL','numcode' => '772','phone_code' => '690'],
			['id' => '200', 'name' => 'TO', 'full_name' => 'Tonga','iso3' => 'TON','numcode' => '776','phone_code' => '676'],
			['id' => '201', 'name' => 'TT', 'full_name' => 'Trinidad and Tobago','iso3' => 'TTO','numcode' => '780','phone_code' => '1868'],
			['id' => '202', 'name' => 'TN', 'full_name' => 'Tunisia','iso3' => 'TUN','numcode' => '788','phone_code' => '216'],
			['id' => '203', 'name' => 'TR', 'full_name' => 'Turkey','iso3' => 'TUR','numcode' => '792','phone_code' => '90'],
			['id' => '204', 'name' => 'TM', 'full_name' => 'Turkmenistan','iso3' => 'TKM','numcode' => '795','phone_code' => '7370'],
			['id' => '205', 'name' => 'TC', 'full_name' => 'Turks and Caicos Islands','iso3' => 'TCA','numcode' => '796','phone_code' => '1649'],
			['id' => '206', 'name' => 'TV', 'full_name' => 'Tuvalu','iso3' => 'TUV','numcode' => '798','phone_code' => '688'],
			['id' => '207', 'name' => 'UG', 'full_name' => 'Uganda','iso3' => 'UGA','numcode' => '800','phone_code' => '256'],
			['id' => '208', 'name' => 'UA', 'full_name' => 'Ukraine','iso3' => 'UKR','numcode' => '804','phone_code' => '380'],
			['id' => '209', 'name' => 'AE', 'full_name' => 'United Arab Emirates','iso3' => 'ARE','numcode' => '784','phone_code' => '971'],
			['id' => '210', 'name' => 'GB', 'full_name' => 'United Kingdom','iso3' => 'GBR','numcode' => '826','phone_code' => '44'],
			['id' => '211', 'name' => 'US', 'full_name' => 'United States','iso3' => 'USA','numcode' => '840','phone_code' => '1'],
			['id' => '212', 'name' => 'UY', 'full_name' => 'Uruguay','iso3' => 'URY','numcode' => '858','phone_code' => '598'],
			['id' => '213', 'name' => 'UZ', 'full_name' => 'Uzbekistan','iso3' => 'UZB','numcode' => '860','phone_code' => '998'],
			['id' => '214', 'name' => 'VU', 'full_name' => 'Vanuatu','iso3' => 'VUT','numcode' => '548','phone_code' => '678'],
			['id' => '215', 'name' => 'VA', 'full_name' => 'Vatican','iso3' => 'VAT','numcode' => '336','phone_code' => '39'],
			['id' => '216', 'name' => 'VE', 'full_name' => 'Venezuela','iso3' => 'VEN','numcode' => '862','phone_code' => '58'],
			['id' => '217', 'name' => 'VN', 'full_name' => 'Viet Nam','iso3' => 'VNM','numcode' => '704','phone_code' => '84'],
			['id' => '218', 'name' => 'VG', 'full_name' => 'Virgin Islands, British','iso3' => 'VGB','numcode' => '92','phone_code' => '1284'],
			['id' => '219', 'name' => 'VI', 'full_name' => 'Virgin Islands, U.s.','iso3' => 'VIR','numcode' => '850','phone_code' => '1340'],
			['id' => '220', 'name' => 'WF', 'full_name' => 'Wallis and Futuna','iso3' => 'WLF','numcode' => '876','phone_code' => '681'],
			['id' => '221', 'name' => 'EH', 'full_name' => 'Western Sahara','iso3' => 'ESH','numcode' => '732','phone_code' => '212'],
			['id' => '222', 'name' => 'YE', 'full_name' => 'Yemen','iso3' => 'YEM','numcode' => '887','phone_code' => '967'],
			['id' => '223', 'name' => 'ZM', 'full_name' => 'Zambia','iso3' => 'ZMB','numcode' => '894','phone_code' => '260'],
			['id' => '224', 'name' => 'ZW', 'full_name' => 'Zimbabwe','iso3' => 'ZWE','numcode' => '716','phone_code' => '263'],
		]);
    }
}
